CREATE TABLE Users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(100) NOT NULL,
    email VARCHAR2(100)  NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    created_at DATE DEFAULT SYSDATE
);

CREATE TABLE Roles (
    role_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR2(50) NOT NULL
);

CREATE TABLE Permissions (
    permission_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permission_name VARCHAR2(50) NOT NULL,
    description VARCHAR2(255)
);

CREATE TABLE User_Roles (
    user_id NUMBER,
    role_id NUMBER,
    PRIMARY KEY (user_id, role_id),
    FOREIGN KEY (user_id) REFERENCES Users(user_id) ON DELETE CASCADE,
    FOREIGN KEY (role_id) REFERENCES Roles(role_id) ON DELETE CASCADE
);

CREATE TABLE Role_Permissions (
    role_id NUMBER,
    permission_id NUMBER,
    PRIMARY KEY (role_id, permission_id),
    FOREIGN KEY (role_id) REFERENCES Roles(role_id) ON DELETE CASCADE,
    FOREIGN KEY (permission_id) REFERENCES Permissions(permission_id) ON DELETE CASCADE
);

CREATE TABLE System_Log (
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER,
    activity VARCHAR2(255) NOT NULL,
    log_time TIMESTAMP DEFAULT SYSTIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES Users(user_id) ON DELETE CASCADE
);

